# Generated by Django 5.2.5 on 2025-08-12 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(verbose_name="Номер места")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Разработчик", "Разработчик"),
                            ("Тестировщик", "Тестировщик"),
                        ],
                        default="office",
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("occupied", "Занято"), ("free", "Свободно")],
                        default="free",
                        max_length=10,
                    ),
                ),
                ("department", models.CharField(max_length=100, verbose_name="Отдел")),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workplaces",
                        to="employees.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
        ),
    ]
