# Generated by Django 5.2.5 on 2025-08-12 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workplace",
            name="department",
        ),
    ]
