# Generated by Django 5.2.5 on 2025-08-12 20:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "middle_name",
                    models.CharField(max_length=100, verbose_name="Отчество"),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Тестировщик", "Тестировщик"),
                            ("Разработчик", "Разработчик"),
                        ],
                        max_length=20,
                        verbose_name="Должность",
                    ),
                ),
                ("department", models.CharField(max_length=200, verbose_name="Отдел")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "hire_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Дата приема"
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
            ],
        ),
    ]
