# Generated by Django 5.2.5 on 2025-08-27 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_skill_employee_skill_level_alter_employee_skills_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="level",
        ),
        migrations.AlterField(
            model_name="employeeskill",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_skills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="employeeskill",
            name="level",
            field=models.PositiveIntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                verbose_name="Уровень владения",
            ),
        ),
        migrations.AlterField(
            model_name="employeeskill",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_skills",
                to="employees.skill",
            ),
        ),
    ]
